x = input('Type something!\n')
print('You entered:' + x)
length = len(x)
print('            ' + '_' * length)
print('          ' + '< ' + x + ' >')
print('            ' + '-' * length)
print('           /')
print('  /\_/\   /')
print(' ( o.o )')
print('  > ^ < ')
